# Generated by Django 4.2.4 on 2023-08-05 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='request',
            name='elevator',
        ),
        migrations.AddField(
            model_name='elevator',
            name='is_door_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elevator',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
