# Generated by Django 4.2.4 on 2023-08-05 10:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0002_remove_floor_direction_remove_request_elevator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=512, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='elevator',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='elevator',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='elevator',
            name='building',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='elevator.building'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='elevator',
            unique_together={('name', 'building')},
        ),
    ]
