# Generated by Django 4.2.4 on 2023-08-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0003_building_alter_elevator_options_alter_elevator_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='current_floor',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
