# Generated by Django 4.2.4 on 2023-08-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0004_alter_elevator_current_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='requests',
            field=models.JSONField(default=list),
        ),
    ]
