# Generated by Django 4.2.4 on 2023-08-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0005_elevator_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='floor_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='elevator',
            name='floors_max',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
