# Generated by Django 4.2.4 on 2023-08-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0006_elevator_floor_min_elevator_floors_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
